### ISSUE TITLE
Aktivere github actions

### ISSUE THREAD

**Issue by arnfinn** [mong/monomongts#9]
Foreløpig kan det gå med 
```
on:
  push:
    paths:
    - 'folder1/**'
  pull_request:
    paths: 
    - 'folder1/**'
```
men må få på plass noe mer sofistikert etterhvert når vi går fra polyrepo til monorepo.
